import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:logger/logger.dart';

import 'background_scan_manager.dart';

/// Generates PowerShell scripts for Windows Task Scheduler operations
///
/// Creates scripts to create, update, and delete scheduled tasks for
/// background email scanning on Windows desktop.
class PowerShellScriptGenerator {
  static final Logger _logger = Logger();

  /// Generate PowerShell script to create a scheduled task
  ///
  /// Creates a script that:
  /// - Registers a scheduled task with Task Scheduler
  /// - Configures trigger based on frequency
  /// - Sets action to launch app with --background-scan flag
  /// - Configures appropriate conditions (user logged in, etc.)
  ///
  /// Returns the path to the generated script file
  static Future<String> generateCreateTaskScript({
    required String taskName,
    required String executablePath,
    required ScanFrequency frequency,
    required String workingDirectory,
  }) async {
    _logger.i('Generating create task script for frequency: ${frequency.label}');

    final trigger = _getTriggerForFrequency(frequency);
    final scriptContent = '''
# PowerShell Script to Create Windows Scheduled Task for Background Scanning
# Generated by Spam Filter Mobile App

\$taskName = "$taskName"
\$executablePath = "$executablePath"
\$workingDirectory = "$workingDirectory"
\$arguments = "--background-scan"

# Create action
\$action = New-ScheduledTaskAction -Execute \$executablePath -Argument \$arguments -WorkingDirectory \$workingDirectory

# Create trigger
$trigger

# Create settings
\$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 5)

# Create principal (run as current user)
\$principal = New-ScheduledTaskPrincipal -UserId "\$env:USERNAME" -LogonType S4U

# Register the task
try {
    Register-ScheduledTask -TaskName \$taskName -Action \$action -Trigger \$trigger -Settings \$settings -Principal \$principal -Force
    Write-Host "SUCCESS: Task '\$taskName' created successfully"
    exit 0
} catch {
    Write-Error "FAILED: Could not create task '\$taskName': \$_"
    exit 1
}
''';

    return await _writeScriptToTempFile(scriptContent, 'create_task.ps1');
  }

  /// Generate PowerShell script to update an existing scheduled task
  ///
  /// Updates the trigger frequency without recreating the entire task
  static Future<String> generateUpdateTaskScript({
    required String taskName,
    required ScanFrequency frequency,
  }) async {
    _logger.i('Generating update task script for frequency: ${frequency.label}');

    final trigger = _getTriggerForFrequency(frequency);
    final scriptContent = '''
# PowerShell Script to Update Windows Scheduled Task Trigger
# Generated by Spam Filter Mobile App

\$taskName = "$taskName"

# Create new trigger
$trigger

try {
    # Get existing task
    \$task = Get-ScheduledTask -TaskName \$taskName -ErrorAction Stop

    # Update trigger
    \$task.Triggers[0] = \$trigger

    # Save changes
    Set-ScheduledTask -TaskName \$taskName -Trigger \$trigger

    Write-Host "SUCCESS: Task '\$taskName' updated successfully"
    exit 0
} catch {
    Write-Error "FAILED: Could not update task '\$taskName': \$_"
    exit 1
}
''';

    return await _writeScriptToTempFile(scriptContent, 'update_task.ps1');
  }

  /// Generate PowerShell script to delete a scheduled task
  static Future<String> generateDeleteTaskScript({
    required String taskName,
  }) async {
    _logger.i('Generating delete task script for task: $taskName');

    final scriptContent = '''
# PowerShell Script to Delete Windows Scheduled Task
# Generated by Spam Filter Mobile App

\$taskName = "$taskName"

try {
    Unregister-ScheduledTask -TaskName \$taskName -Confirm:\$false -ErrorAction Stop
    Write-Host "SUCCESS: Task '\$taskName' deleted successfully"
    exit 0
} catch {
    # Check if error is because task doesn't exist
    if (\$_.Exception.Message -like "*No MSFT_ScheduledTask*") {
        Write-Host "INFO: Task '\$taskName' does not exist (already deleted)"
        exit 0
    } else {
        Write-Error "FAILED: Could not delete task '\$taskName': \$_"
        exit 1
    }
}
''';

    return await _writeScriptToTempFile(scriptContent, 'delete_task.ps1');
  }

  /// Generate PowerShell script to get task status
  static Future<String> generateGetStatusScript({
    required String taskName,
  }) async {
    _logger.i('Generating get status script for task: $taskName');

    final scriptContent = '''
# PowerShell Script to Get Windows Scheduled Task Status
# Generated by Spam Filter Mobile App

\$taskName = "$taskName"

try {
    \$task = Get-ScheduledTask -TaskName \$taskName -ErrorAction Stop
    \$taskInfo = Get-ScheduledTaskInfo -TaskName \$taskName -ErrorAction Stop

    # Output JSON format for parsing
    \$output = @{
        "exists" = \$true
        "state" = \$task.State
        "enabled" = (\$task.Settings.Enabled -eq \$true)
        "lastRunTime" = if (\$taskInfo.LastRunTime) { \$taskInfo.LastRunTime.ToString("o") } else { \$null }
        "nextRunTime" = if (\$taskInfo.NextRunTime) { \$taskInfo.NextRunTime.ToString("o") } else { \$null }
        "lastResult" = \$taskInfo.LastTaskResult
        "triggerFrequency" = if (\$task.Triggers[0].Repetition.Interval) { \$task.Triggers[0].Repetition.Interval } else { "Once" }
    } | ConvertTo-Json

    Write-Host \$output
    exit 0
} catch {
    # Task does not exist
    \$output = @{
        "exists" = \$false
    } | ConvertTo-Json

    Write-Host \$output
    exit 0
}
''';

    return await _writeScriptToTempFile(scriptContent, 'get_status.ps1');
  }

  /// Generate trigger configuration for given frequency
  static String _getTriggerForFrequency(ScanFrequency frequency) {
    switch (frequency) {
      case ScanFrequency.every15min:
        return '''\$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 15) -RepetitionDuration ([TimeSpan]::MaxValue)''';

      case ScanFrequency.every30min:
        return '''\$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 30) -RepetitionDuration ([TimeSpan]::MaxValue)''';

      case ScanFrequency.every1hour:
        return '''\$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Hours 1) -RepetitionDuration ([TimeSpan]::MaxValue)''';

      case ScanFrequency.daily:
        return '''\$trigger = New-ScheduledTaskTrigger -Daily -At "09:00AM"''';

      case ScanFrequency.disabled:
        // Should not happen, but provide fallback
        return '''\$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddDays(365)''';
    }
  }

  /// Write script content to a temporary file
  ///
  /// Creates a temporary .ps1 file that can be executed by PowerShell
  /// Returns the full path to the created file
  static Future<String> _writeScriptToTempFile(
    String content,
    String filename,
  ) async {
    try {
      // Get temp directory
      final tempDir = Directory.systemTemp;
      final scriptPath = path.join(tempDir.path, 'spam_filter_scripts', filename);

      // Create script directory if it does not exist
      final scriptDir = Directory(path.dirname(scriptPath));
      if (!await scriptDir.exists()) {
        await scriptDir.create(recursive: true);
        _logger.d('Created script directory: ${scriptDir.path}');
      }

      // Write script to file
      final scriptFile = File(scriptPath);
      await scriptFile.writeAsString(content);

      _logger.d('PowerShell script written to: $scriptPath');
      return scriptPath;
    } catch (e) {
      _logger.e('Failed to write PowerShell script to temp file', error: e);
      rethrow;
    }
  }

  /// Clean up temporary script files
  ///
  /// Removes the temporary script directory and all scripts within it
  static Future<void> cleanupScripts() async {
    try {
      final tempDir = Directory.systemTemp;
      final scriptDir = Directory(path.join(tempDir.path, 'spam_filter_scripts'));

      if (await scriptDir.exists()) {
        await scriptDir.delete(recursive: true);
        _logger.i('Cleaned up temporary PowerShell scripts');
      }
    } catch (e) {
      _logger.w('Failed to cleanup PowerShell scripts', error: e);
      // Not critical - temp files will be cleaned by system eventually
    }
  }
}
