import 'dart:io';
import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:path/path.dart' as path;
import 'package:logger/logger.dart';

import 'scan_interval.dart';
import '../../util/redact.dart';

/// Generates PowerShell scripts for Windows Task Scheduler operations
///
/// Creates scripts to create, update, and delete scheduled tasks for
/// background email scanning on Windows desktop.
class PowerShellScriptGenerator {
  static final Logger _logger = Logger();

  /// Generate PowerShell script to create a scheduled task
  ///
  /// Creates a script that:
  /// - Registers a scheduled task with Task Scheduler
  /// - Configures trigger based on frequency
  /// - Sets action to launch app with --background-scan flag
  /// - Configures appropriate conditions (user logged in, etc.)
  ///
  /// Returns the path to the generated script file
  static Future<String> generateCreateTaskScript({
    required String taskName,
    required String executablePath,
    required int intervalMinutes,
    required String workingDirectory,
    String? accountId,
    int staggerSlot = 0,
  }) async {
    _logger.i('Generating create task script for interval: ${ScanInterval.label(intervalMinutes)}'
        '${accountId != null ? ' (account: ${Redact.accountId(accountId)})' : ''}');

    final trigger =
        triggerForInterval(intervalMinutes, staggerSlot: staggerSlot);
    // F98 (ADR-0039): the action is account-scoped via --account-id when an
    // accountId is supplied; absent -> legacy bare --background-scan.
    final arguments = accountId != null
        ? '--background-scan --account-id=$accountId'
        : '--background-scan';
    final scriptContent = '''
# PowerShell Script to Create Windows Scheduled Task for Background Scanning
# Generated by MyEmailSpamFilter

\$taskName = "$taskName"
\$executablePath = "$executablePath"
\$workingDirectory = "$workingDirectory"
\$arguments = "$arguments"

# Create action
\$action = New-ScheduledTaskAction -Execute \$executablePath -Argument \$arguments -WorkingDirectory \$workingDirectory

# Create trigger
$trigger

# Create settings
\$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 5)

# Enable Task Scheduler history if not already enabled (requires elevation)
try {
    wevtutil set-log Microsoft-Windows-TaskScheduler/Operational /enabled:true 2>\$null
    if (\$LASTEXITCODE -eq 0) {
        Write-Host "INFO: Enabled Task Scheduler history logging"
    }
} catch {
    # Not critical - history can be enabled manually via Task Scheduler > Enable All Tasks History
}

# Register the task (runs as current user when logged in)
try {
    Register-ScheduledTask -TaskName \$taskName -Action \$action -Trigger \$trigger -Settings \$settings -Force
    Write-Host "SUCCESS: Task '\$taskName' created successfully"
    exit 0
} catch {
    Write-Error "FAILED: Could not create task '\$taskName': \$_"
    exit 1
}
''';

    return await _writeScriptToTempFile(scriptContent, 'create_task.ps1');
  }

  /// Generate PowerShell script to update an existing scheduled task
  ///
  /// Updates the trigger frequency without recreating the entire task
  static Future<String> generateUpdateTaskScript({
    required String taskName,
    required int intervalMinutes,
    int staggerSlot = 0,
  }) async {
    _logger.i('Generating update task script for interval: ${ScanInterval.label(intervalMinutes)}');

    final trigger =
        triggerForInterval(intervalMinutes, staggerSlot: staggerSlot);
    final scriptContent = '''
# PowerShell Script to Update Windows Scheduled Task Trigger
# Generated by MyEmailSpamFilter

\$taskName = "$taskName"

# Create new trigger
$trigger

try {
    # Get existing task
    \$task = Get-ScheduledTask -TaskName \$taskName -ErrorAction Stop

    # Update trigger
    \$task.Triggers[0] = \$trigger

    # Save changes
    Set-ScheduledTask -TaskName \$taskName -Trigger \$trigger

    Write-Host "SUCCESS: Task '\$taskName' updated successfully"
    exit 0
} catch {
    Write-Error "FAILED: Could not update task '\$taskName': \$_"
    exit 1
}
''';

    return await _writeScriptToTempFile(scriptContent, 'update_task.ps1');
  }

  /// Generate PowerShell script to delete a scheduled task
  static Future<String> generateDeleteTaskScript({
    required String taskName,
  }) async {
    _logger.i('Generating delete task script for task: $taskName');

    final scriptContent = '''
# PowerShell Script to Delete Windows Scheduled Task
# Generated by MyEmailSpamFilter

\$taskName = "$taskName"

try {
    Unregister-ScheduledTask -TaskName \$taskName -Confirm:\$false -ErrorAction Stop
    Write-Host "SUCCESS: Task '\$taskName' deleted successfully"
    exit 0
} catch {
    # Check if error is because task doesn't exist
    if (\$_.Exception.Message -like "*No MSFT_ScheduledTask*") {
        Write-Host "INFO: Task '\$taskName' does not exist (already deleted)"
        exit 0
    } else {
        Write-Error "FAILED: Could not delete task '\$taskName': \$_"
        exit 1
    }
}
''';

    return await _writeScriptToTempFile(scriptContent, 'delete_task.ps1');
  }

  /// Generate PowerShell script to get task status
  static Future<String> generateGetStatusScript({
    required String taskName,
  }) async {
    _logger.i('Generating get status script for task: $taskName');

    final scriptContent = '''
# PowerShell Script to Get Windows Scheduled Task Status
# Generated by MyEmailSpamFilter

\$taskName = "$taskName"

try {
    \$task = Get-ScheduledTask -TaskName \$taskName -ErrorAction Stop
    \$taskInfo = Get-ScheduledTaskInfo -TaskName \$taskName -ErrorAction Stop

    # Output JSON format for parsing
    # Include executable path for path verification on app startup
    \$execPath = if (\$task.Actions[0].Execute) { \$task.Actions[0].Execute } else { \$null }

    \$output = @{
        "exists" = \$true
        "state" = \$task.State
        "enabled" = (\$task.Settings.Enabled -eq \$true)
        "lastRunTime" = if (\$taskInfo.LastRunTime) { \$taskInfo.LastRunTime.ToString("o") } else { \$null }
        "nextRunTime" = if (\$taskInfo.NextRunTime) { \$taskInfo.NextRunTime.ToString("o") } else { \$null }
        "lastResult" = \$taskInfo.LastTaskResult
        "triggerFrequency" = if (\$task.Triggers[0].Repetition.Interval) { \$task.Triggers[0].Repetition.Interval } else { "Once" }
        "executablePath" = \$execPath
    } | ConvertTo-Json

    Write-Host \$output
    exit 0
} catch {
    # Task does not exist
    \$output = @{
        "exists" = \$false
    } | ConvertTo-Json

    Write-Host \$output
    exit 0
}
''';

    return await _writeScriptToTempFile(scriptContent, 'get_status.ps1');
  }

  /// Generate trigger configuration for given frequency
  ///
  /// Uses -Once trigger with -RepetitionInterval and -RepetitionDuration
  /// parameters for sub-daily frequencies. The repetition parameters must
  /// be passed directly to New-ScheduledTaskTrigger (not set as properties
  /// after creation, as the Repetition sub-object is null on new triggers).
  ///
  /// ISSUE #161 (Sprint 17): the original trigger was `-Once -At (Get-Date)`,
  /// a suspected (not proven) cause of the task not running on schedule. It
  /// was replaced by a fixed anchor at midnight with repetition.
  ///
  /// **The start is ALWAYS in the past (Sprint 77 Phase 5.1.2 F-PRECHECK
  /// HIGH).** The F264 jitter first used `-At "11:55PM"`, which PowerShell
  /// reads as 23:55 TODAY: for most of the day that is in the future, so a
  /// task for any interval over 15 minutes did not fire until that night (up
  /// to about 22 hours with no scan, while the app said "every 30 minutes").
  /// Task Scheduler runs a repeating trigger at the next repetition after
  /// now only when its start is already past. [startBoundary] computes the
  /// start in Dart and the script receives it as a literal, so the value the
  /// tests check is the value Task Scheduler gets.
  ///
  /// F264 (Sprint 77): ONE trigger shape for every interval. The repetition
  /// interval is the user's minutes, inside Microsoft's documented range for
  /// `RepetitionPattern.Interval` ("The maximum time allowed is 31 days, and
  /// the minimum time allowed is 1 minute"); the app's range is 5 minutes to
  /// 99 hours. The old `-Daily -At 09:00AM` special case is gone: a daily scan
  /// is just 1440 minutes.
  ///
  /// **Jitter (Sprint 77 Q13, Harold: "if > 15 min then random +/- 5
  /// minutes")**: only for intervals over 15 minutes. `-RandomDelay` can only
  /// delay, never advance, so "either way" is built from two parts: the start
  /// time is moved 5 minutes EARLIER (23:55 YESTERDAY, which is in the past)
  /// and `-RandomDelay` adds 0 to 10 minutes, which nets -5 to +5 around the
  /// nominal time. At 15 minutes or less there is no `-RandomDelay` and the
  /// start is exactly midnight today (also in the past).
  ///
  /// **Fixed stagger at 15 minutes or less (Sprint 77 MV-Q2 = 1, Harold).**
  /// Without jitter, every account's task would start at midnight and repeat
  /// on the same minutes, so all accounts would launch together. The start
  /// moves [staggerSlot] x 1 minute later (`ScanInterval.staggerMinutes`;
  /// the slot is saved per account, so it never shifts). This replaces the
  /// F98 (Sprint 42) "interval minus one minute" delay, which Q13 removed.
  /// The database busy timeout, WAL mode and the worker's lock retry (F98)
  /// remain the protection for anything that still overlaps.
  ///
  /// The constants come from `scan_interval.dart`; a test ties them to the
  /// Kotlin alarm's copies.
  static String triggerForInterval(int intervalMinutes,
      {DateTime? now, int staggerSlot = 0}) {
    if (intervalMinutes <= 0) {
      // Should not happen (callers refuse non-positive intervals), but keep a
      // harmless fallback instead of emitting an invalid trigger.
      return r'$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddDays(365)';
    }
    final jitter = ScanInterval.hasJitter(intervalMinutes);
    final start = startBoundary(now ?? DateTime.now(), intervalMinutes,
        staggerSlot: staggerSlot);
    final randomDelay = jitter
        ? ' -RandomDelay (New-TimeSpan -Minutes ${2 * kJitterMinutes})'
        : '';
    return '\$trigger = New-ScheduledTaskTrigger -Once '
        "-At ([datetime]'${powerShellDateTime(start)}') "
        '-RepetitionInterval (New-TimeSpan -Minutes $intervalMinutes) '
        '-RepetitionDuration (New-TimeSpan -Days 365)$randomDelay';
  }

  /// The trigger's start (Task Scheduler `StartBoundary`) for a task
  /// registered at [now]: midnight at the start of [now]'s day, moved
  /// [kJitterMinutes] earlier when the interval has jitter (Q13), or the
  /// [staggerSlot]'s fixed offset later when it does not (MV-Q2). Never later
  /// than [now], so the first run is at most one interval away: an offset
  /// start that is still ahead of [now] (registered in the first minutes
  /// after midnight) moves back one whole day, which keeps the same minutes.
  @visibleForTesting
  static DateTime startBoundary(DateTime now, int intervalMinutes,
      {int staggerSlot = 0}) {
    final midnight = DateTime(now.year, now.month, now.day);
    if (ScanInterval.hasJitter(intervalMinutes)) {
      return midnight.subtract(const Duration(minutes: kJitterMinutes));
    }
    final offset = Duration(
        minutes: ScanInterval.staggerMinutes(intervalMinutes, staggerSlot));
    final start = midnight.add(offset);
    // Calendar day back, not 24 hours, so a DST change cannot move the minute.
    return start.isAfter(now)
        ? DateTime(start.year, start.month, start.day - 1, start.hour,
            start.minute)
        : start;
  }

  /// [value] as `yyyy-MM-ddTHH:mm:ss`. A PowerShell `[datetime]` cast parses
  /// with the invariant culture, so this literal reads the same on every
  /// Windows display language; the value is local time, as Task Scheduler
  /// expects.
  @visibleForTesting
  static String powerShellDateTime(DateTime value) {
    String two(int n) => n.toString().padLeft(2, '0');
    return '${value.year.toString().padLeft(4, '0')}-${two(value.month)}-'
        '${two(value.day)}T${two(value.hour)}:${two(value.minute)}:'
        '${two(value.second)}';
  }

  /// Write script content to a temporary file
  ///
  /// Creates a temporary .ps1 file that can be executed by PowerShell
  /// Returns the full path to the created file
  /// Write an arbitrary PowerShell [script] to a temp file and return its path
  /// (Sprint 42, F98 -- used for the enumerate-account-tasks query). Cleaned up
  /// by [cleanupScripts] like the other generated scripts.
  static Future<String> writeAdHocScript(String script) async {
    return _writeScriptToTempFile(script, 'adhoc_query.ps1');
  }

  static Future<String> _writeScriptToTempFile(
    String content,
    String filename,
  ) async {
    try {
      // Get temp directory
      final tempDir = Directory.systemTemp;
      final scriptPath = path.join(tempDir.path, 'spam_filter_scripts', filename);

      // Create script directory if it does not exist
      final scriptDir = Directory(path.dirname(scriptPath));
      if (!await scriptDir.exists()) {
        await scriptDir.create(recursive: true);
        _logger.d('Created script directory: ${scriptDir.path}');
      }

      // Write script to file
      final scriptFile = File(scriptPath);
      await scriptFile.writeAsString(content);

      _logger.d('PowerShell script written to: $scriptPath');
      return scriptPath;
    } catch (e) {
      _logger.e('Failed to write PowerShell script to temp file', error: e);
      rethrow;
    }
  }

  /// Clean up temporary script files
  ///
  /// Removes the temporary script directory and all scripts within it
  static Future<void> cleanupScripts() async {
    try {
      final tempDir = Directory.systemTemp;
      final scriptDir = Directory(path.join(tempDir.path, 'spam_filter_scripts'));

      if (await scriptDir.exists()) {
        await scriptDir.delete(recursive: true);
        _logger.i('Cleaned up temporary PowerShell scripts');
      }
    } catch (e) {
      _logger.w('Failed to cleanup PowerShell scripts', error: e);
      // Not critical - temp files will be cleaned by system eventually
    }
  }
}
